FROM node:12-alpine

COPY median.js /app/median.js
COPY reports /app/reports

WORKDIR /app

ENV NODE_PATH /usr/local/lib/node_modules
RUN npm -g install lighthouse@7

ENTRYPOINT ["node", "median.js"]
